#!/bin/bash

echo "Run GDB in another terminal. Connect to localhost:1234"
qemu-system-x86_64 -m 1024 -device ide-hd,drive=hd0,cyls=512,heads=4,secs=32 -drive file=build/TigerOS.img,format=raw,id=hd0,media=disk,if=none -s -S
