#!/bin/sh

qemu-system-i386 -debugcon stdio -m 1024 -device ide-hd,drive=hd0,cyls=131,heads=16,secs=63 -drive file=build/TigerOS.img,format=raw,id=hd0,media=disk,if=none
echo # Print an extra newline
