.\" TDISK Man Pages
.\" By tigercodes-dev
.\" TDISK is included in TigerOS

.TH "TDISK-SET-ACTIVE" "8" "2026-4-18" "TigerOS 0.2.1" "System Administration"

.SH NAME
tdisk-set-active \- mark a partition as active or bootable.

.SH SYNOPSIS
.B tdisk set-active
.I partition-num
[-d | --deactivate]
[-n | --no-deactivate-others]

.SH DESCRIPTION
The \fBset-active\fR command sets a disk partition as active. MBR partition table entries have one bit that tells if the partition is bootable. The MBR bootstrap code will check for which partition is bootable and boot from it. Typically, there is only one bootable partition.

This command will set the active bit on the partition entry and deactivate all other partitions unless the \fB-n\fR option is specified. However, there usually should only be one bootable partition; otherwise, the MBR bootstrap code may ask for which one to boot, or choose automatically.

.SH OPTIONS

partition-num
.RS 4
The partition number to set active. Use \fBtdisk list-partitions\fR to see the partition numbers.
.RE

-d, --deactivate
.RS 4
Set the partition as not active instead of active.
.RE

-n, --no-deactivate-others
.RS 4
Do not deactivate the other partitions when marking one as active.
.RE

.SH AUTHOR

\fBtdisk\fR was created by tigercodes-dev \fB<https://github.com/tigercodes-dev>\fR as part of the TigerOS project.

.SH SEE ALSO

\fBtdisk-mbr\fR(8) \fBtdisk-list-partitions\fR(8) \fBtdisk-create-partitions\fR(8)