.\" TDISK Man Pages
.\" By tigercodes-dev
.\" TDISK is included in TigerOS

.TH "TDISK-WRITE-SECTORS" "8" "2026-4-26" "TigerOS 0.2.2" "System Administration"

.SH NAME
tdisk-write-sectors \- write sectors to a disk or disk image.

.SH SYNOPSIS
.B tdisk write-sectors
.I lba
.I count
[-i | --input \fIfile\fR]

.SH DESCRIPTION
The \fBwrite-sectors\fR command writes 512-byte sectors to a disk. To determine where to write, an LBA sector address is used.
LBA (Logical Block Addressing) addresses sectors by a sector number, starting at 0. LBA is the preferred addressing scheme over the deprecated CHS (Cylinder Head Sector) scheme because it does not rely on disk geometry which varies based on hardware.

By default, written data will be obtained from \fBstdin\fR; however, using the \fB-i\fR flag and specifying a file will instead write data from the specified file onto the disk.

.SH OPTIONS

lba
.RS 4
The \fBLogical Block Address\fR of the first sector to read. The number of the first is sector 0.
.RE

count
.RS 4
The number of sectors to read. This value must be greater than 0 to read any data.
.RE

-i, --input \fIfile\fR
.RS 4
Obtain data to write from a file instead of \fBstdin\fR.
.RE

.SH AUTHOR

\fBtdisk\fR was created by tigercodes-dev \fB<https://github.com/tigercodes-dev>\fR as part of the TigerOS project.

.SH SEE ALSO

\fBtdisk-read-sectors\fR(8)
