.\" TDISK Man Pages
.\" By tigercodes-dev
.\" TDISK is included in TigerOS

.TH "TDISK-CREATE-PARTITION" "8" "2026-4-18" "TigerOS 0.2.1" "System Administration"

.SH NAME
tdisk-create-partiton \- create a new partition on a disk

.SH SYNOPSIS
.B tdisk create-partition
.I type
[-s | --size \fIsize\fR]
[-f | --first \fIoffset\fR]
[-t | --type \fItype\fR]

.SH DESCRIPTION
The \fBcreate-partition\fR command is used to add a new partition to a disk. Partitions are subdivisions of a disk that each can act independently.

On a disk using MBR partitioning, partitions are listed in the partition table located in the first sector of the disk. MBR partitioning supports up to \fB4 primary partitions\fR, however more partitions can be added using extended partitions. Currently, extended partitions are not supported by \fBtdisk\fR, but you still need to specify 'primary' in the first partition type field.

If a size is not specified with \fB-s\fR, the partition will take up all of the remaining disk space. You can also specify an offset before the start of the partition with \fB-f\fR. The \fBsize\fR and \fBoffset\fR fields can use the units \fBK,M,G,T\fR (kibibyte, mebibyte, gibibyte, tebibyte) or \fBS\fR (sectors).

The type field allows to specify a partition system type / ID. This type is used to specify the filesystem or purpose of the partition. (e.g. FAT32, Linux, NTFS). We are working towards adding support for all partition types in the type field, but only some are available currently.

.SH OPTIONS

type
.RS 4
The partition type (primary/extended). Only primary is supported currently.
.RE

-s, --size \fIsize\fR
.RS 4
Set the size of the partition instead of using the full size available. Unit suffixes can be used in this field.
.RE

-f, --first \fIoffset\fR
.RS 4
Add offset between the first available sector and the first sector used in the partition.
.RE

-t, --type \fItype\fR
.RS 4
Set the partition system type / system ID. Not all of the existing types are supported yet.
Available types are None/Empty, FAT12, FAT16, FAT16B, and FAT32 CHS.
More recognized partition types will be added soon.
.RE

.SH AUTHOR

\fBtdisk\fR was created by tigercodes-dev \fB<https://github.com/tigercodes-dev>\fR as part of the TigerOS project.

.SH SEE ALSO

\fBtdisk-mbr\fR(8)
